version: "3"

services:

    web-mvc:
      image: robottr/robottr-web-mvc:latest
      container_name: robottr-web-mvc
      build:
        context: ../src
        dockerfile: ./RobotTR/Web/RobotTR.Portal.MVC/Dockerfile
      ports:
        - "6001:6001"
      environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - ASPNETCORE_URLS=http://*:6001